### ISSUE TITLE
Fix mappings - check/fix ignore_above

### ISSUE THREAD

**Issue by plopezgarcia** [bst-mug/trec2017#28]
In general, check all mappings. Be particularly careful with this property: https://www.elastic.co/guide/en/elasticsearch/reference/current/ignore-above.html

It defaults to 256, so me might be ignoring some long abstracts:

http://HOST:9200/trec?pretty

**Comment by michelole** [comment]
This might be related to the subfield "keyword", indexed with type `keyword` for sorting/aggregation.
