### ISSUE TITLE
Create gold standard out of extra topics

### ISSUE THREAD

**Issue by michelole** [bst-mug/trec2017#30]
Create a separate gold standard (in qrels format) out of the recently published [extra topics](http://trec-cds.appspot.com/extra_topics2017.pdf).

**Comment by kasac** [comment]
Thank you Michel,

i am looking into it ASAP. :)

-Zdenko

**Comment by michelole** [comment]
Hi @kasac!

A [small gold standard](http://trec-cds.appspot.com/extra_topics2017.pdf) was published and I already imported it into the system.

Maybe you could take a look at them to better tune your brain while evaluating the [final topic set](http://trec-cds.appspot.com/topics2017.xml), which has no gold standard so far.

I went ahead and created issue #33 in case you are interested. 😃
