### ISSUE TITLE
Is relevance broken?

### ISSUE THREAD

**Issue by michelole** [bst-mug/trec2017#34]
Consider evaluating whether [relevance is broken](https://www.elastic.co/guide/en/elasticsearch/guide/current/relevance-is-broken.html) in our case due to `idf` being distributed over 5 shards.

I would prefer to be on the safe side and either:
- Reindex with only 1 shard
- Add `?search_type=dfs_query_then_fetch` to all queries

**Comment by michelole** [comment]
@plopezgarcia your comment here would be appreciated.

**Comment by plopezgarcia** [comment]
Having only 1 shard doesn't make much sense in real production systems and adding that `search_type` parameter is not recommended either, the article says.

Directly from the article:

> In practice, this is not a problem. The differences between local and global IDF diminish the more documents that you add to the index. With real-world volumes of data, the local IDFs soon even out. The problem is not that relevance is broken but that there is too little data.

With several millions documents in our case, I would not worry at all about this. Did you encounter any particular problem?

In any case, as I will probably have to reindex at some point and we don't have scalability needs, I can easily make it 1 shard.

**Comment by michelole** [comment]
Reindexing with only 1 shard could lead to performance issues that would impact development.

Considering so far this is just a theoretical problem, I propose that we use `?search_type=dfs_query_then_fetch` and go ahead.

Closing and marking as won't fix, feel free to reopen if you disagree.
