### ISSUE TITLE
Move elasticsearch with data to the cloud

### ISSUE THREAD

**Issue by plopezgarcia** [bst-mug/trec2017#5]
Move elasticsearch with all indexed data to the cloud so we can all try different queries, etc.

**Comment by michelole** [comment]
There's a way to move the index around, without need to reindex the docs.

E.g. Wikipedia ElasticSearch indexes are available at https://dumps.wikimedia.org/other/cirrussearch/

**Comment by plopezgarcia** [comment]
That's good to know, thanks. Unfortunately, it takes 10x longer to transfer our 40GB index than to reindex all documents... (at home internet upload speed - we can check from the MedUni).

**Comment by michelole** [comment]
Fixed?
