### ISSUE TITLE
Reduce the weight of abstract size 

### ISSUE THREAD

**Issue by michelole** [bst-mug/trec2017#71]
https://www.ncbi.nlm.nih.gov/pubmed/15085719 is top-10 ranked for topic 1, but does not even mention the gene.

However, it's probably well ranked due to its small size. Experiment reducing this weight.

**Comment by kasac** [comment]
“as fart as possible” :-D

I would rank it max as partially relevant, I agree with u.

LG
Z

**Comment by michelole** [comment]
We have two options:

1. Disable [field-length norm](https://www.elastic.co/guide/en/elasticsearch/guide/current/scoring-theory.html#field-norm).
2. Use BM25 (#86) as similarity measure and [set `b` to zero](https://stackoverflow.com/a/38362244).

I would go with the second.

Any option to reduce the weight implies reindexing.

**Comment by michelole** [comment]
[How to set `b`](https://www.elastic.co/guide/en/elasticsearch/guide/master/changing-similarities.html)

**Comment by michelole** [comment]
Setting B = 0 in the Okapi BM25 ranking algorithm worsened results from 0,7693 to 0,6852.

Also, the documents are longer and take more time to evaluate.
