### ISSUE TITLE
Zdenko's Keywords

### ISSUE THREAD

**Issue by michelole** [bst-mug/trec2017#79]
@kasac has provided the following:

search "synonyms"
amplification, amplified coamplified
atypical lipomatous tumor, liposarcoma, well-differentiated liposarcoma, dedifferentiated liposarcoma

use umbrella terms in titles (liposarcoma --> sarcomas/ [malignant] soft tissue tumors)

relevance markers:
therapy, prognostic, prognosis,recurrence-free survival, *therap*; chemotherapy; chemotherapeutical
tumor, tumour, cancer, cancers, carcinoma, carcinomas, neoplasm, neoplasms,

**Comment by kasac** [comment]
These are also more systematically in the gold standard sheet as a new tab.

Cheers,
Zdenko
